"""add published options table

Revision ID: 7284f700d78b
Revises: 3a816f3b5f49
Create Date: 2026-10-05 18:23:47.074074

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7284f700d78b"
down_revision: Union[str, Sequence[str], None] = "3a816f3b5f49"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "published_options",
        sa.Column("version", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("version", name=op.f("pk_published_options")),
        schema="cv",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("published_options", schema="cv")
    # ### end Alembic commands ###
