name: CI

on:
  pull_request:
    branches: [main]
  workflow_call:
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      database:
        image: postgres:18
        env:
          POSTGRES_DB: site_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d site_db"
          --health-interval 2s
          --health-timeout 3s
          --health-retries 15
    env:
      DATABASE__HOST: localhost
      DATABASE__USER: postgres
      DATABASE__PASSWORD: postgres
      DATABASE__NAME: site_db
      REDIS__HOST: localhost
      REDIS__PASSWORD: dev
      S3__ACCESS_KEY_ID: GK3034edd8dc6fd1fd46c3ef25 # Dummy id
      S3__SECRET_ACCESS_KEY: 62baee66f3c5526c5f47fa5b9379ee25609c13dde3837ace75bf833aaac717a4 # Dummy key
      S3__BUCKET: bucket
      CONTACT__EMAIL: ci-dummy@example.com
      CONTACT__PHONE: +45 00 00 00 00
      CONTACT__LINKEDIN: https://www.example.com/in/ci-dummy
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
      - run: uv sync --locked
      - run: uv run ruff check
      - run: uv run mypy
      - run: uv run pytest
